
POST http://localhost:3000/api/save-data
Content-Type: application/json

{
  "generatedAt": "2025-07-24T19:42:36.984Z",
  "groups": [
    {
      "words": [
        "regla",
        "borrador",
        "lapiz",
        "cartuchera",
        "silla"
      ]
    },
    {
      "words": [
        "azul",
        "rojo",
        "verde",
        "amarillo"
      ]
    },
    {
      "words": [
        "correr",
        "saltar",
        "caminar"
      ]
    }
  ]
}
